
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES (N'Đen', CAST(N'2023-11-15' AS Date), N'Thương hiệu đồng hồ nổi tiếng đến từ Nhật Bản không ngừng cải tiến và cho ra mắt những dòng sản phẩm chất lượng phù hợp với nhiều đối tượng khách hàng. Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao, Edifice thiết kế hiện đại cùng nhiều tính năng vượt trội, Sheen với thiết kế cổ điển và sang trọng,…', 20, N'Kính Sapphire', 44, N'Hợp kim nhôm', N'MTP-E715D-7AVDF', N'Cấu hình Đồng hồ Casio 43.4 mm Nam MTP-E715D-7AVDF', N'Nhật Bản', 3726000, 0.015, 50, 44, 0, CAST(N'2023-11-15' AS Date), 12, N'Thép không gỉ', 4)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES (N'Đen', CAST(N'2023-11-15' AS Date), N'Thương hiệu đồng hồ nổi tiếng đến từ Nhật Bản không ngừng cải tiến và cho ra mắt những dòng sản phẩm chất lượng phù hợp với nhiều đối tượng khách hàng. Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao, Edifice thiết kế hiện đại cùng nhiều tính năng vượt trội, Sheen với thiết kế cổ điển và sang trọng,…', 20, N'Kính Sapphire', 44, N'Hợp kim nhôm', N'Unisex A168WER-2ADF', N'Cấu hình Đồng hồ Casio 38.6 x 36.3 mm Unisex A168WER-2ADF', N'Nhật Bản', 1633000, 0.015, 50, 44, 0, CAST(N'2023-11-15' AS Date), 12, N'Thép không gỉ', 4)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES (N'Bạc', CAST(N'2023-11-15' AS Date), N'Thương hiệu đồng hồ nổi tiếng đến từ Nhật Bản không ngừng cải tiến và cho ra mắt những dòng sản phẩm chất lượng phù hợp với nhiều đối tượng khách hàng. Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao, Edifice thiết kế hiện đại cùng nhiều tính năng vượt trội, Sheen với thiết kế cổ điển và sang trọng,…', 20, N'Kính Sapphire', 44, N'Da tổng hợp', N'MTP-E725L-8AVDF', N'Cấu hình Đồng hồ Casio 42 mm Nam MTP-E725L-8AVDF', N'Nhật Bản', 2739000, 0.015, 50, 44, 0, CAST(N'2023-11-15' AS Date), 12, N'Thép không gỉ', 4)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES (N'Bạc', CAST(N'2023-11-15' AS Date), N'Thương hiệu đồng hồ nổi tiếng đến từ Nhật Bản không ngừng cải tiến và cho ra mắt những dòng sản phẩm chất lượng phù hợp với nhiều đối tượng khách hàng. Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao, Edifice thiết kế hiện đại cùng nhiều tính năng vượt trội, Sheen với thiết kế cổ điển và sang trọng,…', 20, N'Kính Sapphire', 44, N'Da tổng hợp', N'MTP-M100L-1AVDF', N'Cấu hình Đồng hồ Casio 42.5 mm Nam MTP-M100L-1AVDF', N'Nhật Bản', 3085000, 0.015, 50, 44, 0, CAST(N'2023-11-15' AS Date), 12, N'Thép không gỉ', 4)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES (N'Bạc', CAST(N'2023-11-15' AS Date), N'Thương hiệu đồng hồ nổi tiếng đến từ Nhật Bản không ngừng cải tiến và cho ra mắt những dòng sản phẩm chất lượng phù hợp với nhiều đối tượng khách hàng. Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao, Edifice thiết kế hiện đại cùng nhiều tính năng vượt trội, Sheen với thiết kế cổ điển và sang trọng,…', 20, N'Kính Sapphire', 44, N'Da tổng hợp', N'WS-1600H-1AVDF', N'Đồng hồ Casio 42.1 mm Nam WS-1600H-1AVDF', N'Nhật Bản', 1210000, 0.015, 50, 44, 0, CAST(N'2023-11-15' AS Date), 12, N'Thép không gỉ', 4)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES (N'Bạc', CAST(N'2023-11-15' AS Date), N'Đồng hồ thông minh GPS tích hợp tính năng sạc bằng năng lượng mặt trời.Phiên bản One Piece Zoro mang tới sự khác biệt về diện mạo và màu sắcKhả năng kháng nước 10ATM cực tốt, chịu nhiệt và chống sốc ấn tượngNâng cao thể lực với chế độ tập luyện: chạy bộ, đạp xe, bơi lội, pilatesHệ thống định vị cao cấp GPS, GLONASS, Galileo; màn hình chống chóiTheo dõi giấc ngủ, theo dõi sức khỏe phụ nữ, đo nồng độ oxy trong máu. Ứng dụng Garmin Connect kết nối và thống kê chỉ số sức khỏe, tập luyện', 22, N'Kính Sapphire', 44, N'Da tổng hợp', N'INSTINCT2SOLAR', N'Đồng hồ thông minh Garmin Instinct 2 Solar, One Piece Zoro, Rabbit', N'Đài Loan', 11210000, 0.015, 50, 44, 0, CAST(N'2023-11-15' AS Date), 12, N'Thép không gỉ', 3)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES (N'Bạc', CAST(N'2023-11-15' AS Date), N'Đồng hồng thông minh Samsung thiết kế hết mực trẻ trung và năng động.Màn hình lớn với tấm nền Super AMOLED hiển thị nội dung rõ ràng, sắc nét.Viền bezel nhôm mỏng nhẹ, mặt kính Sapphire chống xước và chịu lực tốt.Dây đeo One Click Band có khóa bấm dễ dàng thay đổi dây trong tích tắc.Theo dõi sức khỏe toàn diện với hàng loạt cảm biến và các tính năng thông minh.Viên pin 425mAh cho thời gian sử dụng lên đến 40 giờ (khi tắt Always On Display).Kháng nước chuẩn 5ATM cho bạn yên tâm khi đeo đi mưa, đi tắm, đi bơi', 10, N'Kính Sapphire', 44, N'Da tổng hợp', N'INSTINCT2SOLAR', N'Đồng hồ thông minh Samsung Galaxy Watch6 Bluetooth 44mm Bạc', N'Việt Nam', 7490000, 0.015, 100, 44, 0, CAST(N'2023-11-15' AS Date), 12, N'Thép không gỉ', 1)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES (N'Bạc', CAST(N'2023-11-15' AS Date), N'Apple Watch Series 8 diện mạo đẹp sang trọng, màu sắc thời thượng.Viền và dây đồng hồ làm bằng chất liệu thép, bền chắc theo năm tháng
Tích hợp eSIM, nghe gọi ngay trên đồng hồ không cần kết nối điện thoại.Màn hình Retina sắc nét, màn hình luôn bật giúp xem thông báo dễ dàng
Trang bị cảm biến nhiệt, khả năng đo các chỉ số sức khỏe chính xác hơn.Nhiều tính năng theo dõi sức khỏe: giấc ngủ, đo nhịp tim, oxy trong máu,v.v.Kháng bụi IP6X, chống nước đến 50m, thoải mái dùng ở hồ bơi, ngoài trời', 10, N'Kính Sapphire', 44, N'Da tổng hợp', N'MNJ83VN/A
', N'Apple Watch S8 LTE 41mm viền thép dây thép Bạc MNJ83VN/A', N'Việt Nam', 21990000, 0.015, 100, 44, 0, CAST(N'2023-11-15' AS Date), 12, N'Thép không gỉ', 2)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES (N'Bạc', CAST(N'2023-11-15' AS Date), N'Apple Watch Series 8 diện mạo đẹp sang trọng, màu sắc thời thượng.Viền và dây đồng hồ làm bằng chất liệu thép, bền chắc theo năm tháng
Tích hợp eSIM, nghe gọi ngay trên đồng hồ không cần kết nối điện thoại.Màn hình Retina sắc nét, màn hình luôn bật giúp xem thông báo dễ dàng
Trang bị cảm biến nhiệt, khả năng đo các chỉ số sức khỏe chính xác hơn.Nhiều tính năng theo dõi sức khỏe: giấc ngủ, đo nhịp tim, oxy trong máu,v.v.Kháng bụi IP6X, chống nước đến 50m, thoải mái dùng ở hồ bơi, ngoài trời', 10, N'Kính Sapphire', 44, N'Da tổng hợp', N'MQFM3VN/A', N'Apple Watch Ultra LTE 49mm viền Titanium dây Orange Alpine Loop size L MQFM3VN/A
', N'Việt Nam', 23490000, 0.015, 100, 44, 0, CAST(N'2023-11-15' AS Date), 12, N'Thép không gỉ', 2)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Bạc', CAST(N'2023-11-15' AS Date), N'Apple Watch Series 8 diện mạo đẹp sang trọng, màu sắc thời thượng.Viền và dây đồng hồ làm bằng chất liệu thép, bền chắc theo năm tháng
Tích hợp eSIM, nghe gọi ngay trên đồng hồ không cần kết nối điện thoại.Màn hình Retina sắc nét, màn hình luôn bật giúp xem thông báo dễ dàng
Trang bị cảm biến nhiệt, khả năng đo các chỉ số sức khỏe chính xác hơn.Nhiều tính năng theo dõi sức khỏe: giấc ngủ, đo nhịp tim, oxy trong máu,v.v.Kháng bụi IP6X, chống nước đến 50m, thoải mái dùng ở hồ bơi, ngoài trời', 10, N'Kính Sapphire', 44, N'Da tổng hợp', N'MR8W3SA/A', N'Apple Watch Series 9 GPS 41mm viền nhôm dây cao su Midnight S/M', N'Việt Nam', 1990000, 0.015, 100, 44, 0, CAST(N'2023-11-15' AS Date), 12, N'Thép không gỉ', 2)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Bạc', CAST(N'2023-11-15' AS Date), N'Thương hiệu đồng hồ nổi tiếng đến từ Nhật Bản không ngừng cải tiến và cho ra mắt những dòng sản phẩm chất lượng phù hợp với nhiều đối tượng khách hàng. Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao, Edifice thiết kế hiện đại cùng nhiều tính năng vượt trội, Sheen với thiết kế cổ điển và sang trọng,…', 20, N'Kính Sapphire', 44, N'Da tổng hợp', N'MTP-E350D-7BVDF', N'Cấu hình Đồng hồ CASIO 40.6 mm Nam MTP-E350D-7BVDF', N'Việt Nam', 3050000, 0.015, 100, 44, 0, CAST(N'2023-11-15' AS Date), 12, N'Thép không gỉ', 4)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Bạc', CAST(N'2023-11-15' AS Date), N'Màn hình AMOLED 1,3'''' cho hiển thị sống động, sắc nét, ngay cả dưới ánh nắng chói chang.Duy trì cuộc phiêu lưu với thời lượng pin cao lên đến 16 ngày ở chế độ đồng hồ thông minh.Theo dõi sức khỏe toàn diện: Đo nhịp tim trên cổ tay, nhịp thở, độ bão hòa oxy trong máu, v.v.Tích hợp nhiều môn thể thao, bài tập cardio, rèn sức bền, yoga,... bằng hoạt ảnh sinh động.Định vị vị trí của bạn nhanh chóng, chính xác nhờ mạng lưới vệ tinh GPS, GLONASS, Galileo.Vạch lộ trình cho mọi cuộc phiêu lưu với: ClimbPro, Bản đồ Topo lục địa, Lộ trình khứ hồi,v.v', 20, N'Kính Sapphire', 44, N'Da tổng hợp', N'EPIX(GEN2)', N'Đồng hồ Garmin Epix (Gen 2) Trắng Carrera', N'Việt Nam', 24990000, 0.015, 100, 44, 0, CAST(N'2023-11-15' AS Date), 12, N'Thép không gỉ', 3)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Bạc', CAST(N'2023-11-16' AS Date), N'Màn hình AMOLED 1,3'''' cho hiển thị sống động, sắc nét, ngay cả dưới ánh nắng chói chang.Duy trì cuộc phiêu lưu với thời lượng pin cao lên đến 16 ngày ở chế độ đồng hồ thông minh.Theo dõi sức khỏe toàn diện: Đo nhịp tim trên cổ tay, nhịp thở, độ bão hòa oxy trong máu, v.v.Tích hợp nhiều môn thể thao, bài tập cardio, rèn sức bền, yoga,... bằng hoạt ảnh sinh động.Định vị vị trí của bạn nhanh chóng, chính xác nhờ mạng lưới vệ tinh GPS, GLONASS, Galileo.Vạch lộ trình cho mọi cuộc phiêu lưu với: ClimbPro, Bản đồ Topo lục địa, Lộ trình khứ hồi,v.v', 7, N'Kính Sapphire', 44, N'Da tổng hợp', N'WATCH6CLASSIC47MMBT (SM-R960)', N'Đồng hồ thông minh Samsung Galaxy Watch6 Classic Bluetooth 47mm Bạc', N'Việt Nam', 9490000, 0.015, 100, 44, 0, CAST(N'2023-11-16' AS Date), 12, N'Thép không gỉ', 1)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Bạc', CAST(N'2023-11-16' AS Date), N'Màn hình AMOLED 1,3'''' cho hiển thị sống động, sắc nét, ngay cả dưới ánh nắng chói chang.Duy trì cuộc phiêu lưu với thời lượng pin cao lên đến 16 ngày ở chế độ đồng hồ thông minh.Theo dõi sức khỏe toàn diện: Đo nhịp tim trên cổ tay, nhịp thở, độ bão hòa oxy trong máu, v.v.Tích hợp nhiều môn thể thao, bài tập cardio, rèn sức bền, yoga,... bằng hoạt ảnh sinh động.Định vị vị trí của bạn nhanh chóng, chính xác nhờ mạng lưới vệ tinh GPS, GLONASS, Galileo.Vạch lộ trình cho mọi cuộc phiêu lưu với: ClimbPro, Bản đồ Topo lục địa, Lộ trình khứ hồi,v.v', 7, N'Kính Sapphire', 44, N'Da tổng hợp', N'WATCH6CLASSIC47MMBT (SM-R960)', N'Đồng hồ thông minh Samsung Galaxy Watch6 Classic Bluetooth 47mm Đen', N'Việt Nam', 9490000, 0.015, 100, 44, 0, CAST(N'2023-11-16' AS Date), 12, N'Thép không gỉ', 1)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Bạc', CAST(N'2023-11-16' AS Date), N'Thiết kế vòng đeo tay nhỏ gọn và siêu nhẹ
Màn hình hiển thị nội dung tốt.Khả năng theo dõi thống kê thông tin tập luyện.Theo dõi xuyên suốt và nâng cao sức khỏe.Thời lượng pin hoạt động liên tục đến 7 ngày', 49, N'Kính Sapphire', 44, N'Da tổng hợp', N'SM-R375', N'Samsung Galaxy Fit E đen', N'Việt Nam', 990000, 0.015, 100, 44, 0, CAST(N'2023-11-16' AS Date), 12, N'Thép không gỉ', 1)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Bạc', CAST(N'2023-11-16' AS Date), N'Thiết kế vòng đeo tay nhỏ gọn và siêu nhẹ
Màn hình hiển thị nội dung tốt.Khả năng theo dõi thống kê thông tin tập luyện.Theo dõi xuyên suốt và nâng cao sức khỏe.Thời lượng pin hoạt động liên tục đến 7 ngày', 22, N'Kính Sapphire', 44, N'Da tổng hợp', N'VENUSQ2', N'Đồng hồ thông minh Garmin Venu Sq 2 Music, Đen/Đá phiến', N'Việt Nam', 7690000, 0.015, 100, 44, 0, CAST(N'2023-11-16' AS Date), 12, N'Thép không gỉ', 3)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Hồng phấn', CAST(N'2023-11-16' AS Date), N'Thiết kế vòng đeo tay nhỏ gọn và siêu nhẹ
Màn hình hiển thị nội dung tốt.Khả năng theo dõi thống kê thông tin tập luyện.Theo dõi xuyên suốt và nâng cao sức khỏe.Thời lượng pin hoạt động liên tục đến 7 ngày', 5, N'Kính Sapphire', 44, N'Da tổng hợp', N'FORERUNNER255S', N'Đồng hồ thông minh Garmin Forerunner 255S, GPS, Hồng phấn', N'Việt Nam', 8990000, 0.015, 100, 44, 0, CAST(N'2023-11-16' AS Date), 12, N'Thép không gỉ', 3)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Xanh Bạc Hà', CAST(N'2023-11-16' AS Date), N'Thiết kế vòng đeo tay nhỏ gọn và siêu nhẹ
Màn hình hiển thị nội dung tốt.Khả năng theo dõi thống kê thông tin tập luyện.Theo dõi xuyên suốt và nâng cao sức khỏe.Thời lượng pin hoạt động liên tục đến 7 ngày', 5, N'Kính Sapphire', 44, N'Da tổng hợp', N'VENUSQ2', N'Đồng hồ thông minh Garmin Venu Sq 2 Xanh Bạc Hà', N'Việt Nam', 6490000, 0.015, 100, 44, 0, CAST(N'2023-11-16' AS Date), 12, N'Thép không gỉ', 3)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Bạc', CAST(N'2023-11-16' AS Date), N'Thiết kế vòng đeo tay nhỏ gọn và siêu nhẹ
Màn hình hiển thị nội dung tốt.Khả năng theo dõi thống kê thông tin tập luyện.Theo dõi xuyên suốt và nâng cao sức khỏe.Thời lượng pin hoạt động liên tục đến 7 ngày', 5, N'Kính Sapphire', 44, N'Da tổng hợp', N'Unisex A168WER-2ADF', N'Đồng hồ Casio 38.6 x 36.3 mm Unisex A168WER-2ADF', N'Việt Nam', 1630000, 0.015, 100, 44, 0, CAST(N'2023-11-16' AS Date), 12, N'Thép không gỉ', 4)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Đen Hồng', CAST(N'2023-11-16' AS Date), N'Thiết kế vòng đeo tay nhỏ gọn và siêu nhẹ
Màn hình hiển thị nội dung tốt.Khả năng theo dõi thống kê thông tin tập luyện.Theo dõi xuyên suốt và nâng cao sức khỏe.Thời lượng pin hoạt động liên tục đến 7 ngày', 5, N'Kính Sapphire', 44, N'Da tổng hợp', N'LW-204-1ADF', N'Đồng hồ Casio 35 mm Nữ LW-204-1ADF', N'Việt Nam', 1030000, 0.015, 100, 44, 0, CAST(N'2023-11-16' AS Date), 12, N'Thép không gỉ', 4)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Đen', CAST(N'2023-11-17' AS Date), N'Samsung đã cho ra mắt chiếc smartwatch có tên gọi là Galaxy Watch5 Pro LTE 45mm. Với những thay đổi về mặt thiết kế, chức năng theo dõi sức khỏe 24/7, đa dạng chế độ thể thao và hệ thống vệ tinh hiện đại hứa hẹn vẫn là sản phẩm làm hài lòng các tín đồ yêu công nghệ.', 12, N'Kính Sapphire', 44, N'Da tổng hợp', N'Samsung Galaxy Watch5 Pro', N'Đồng hồ thông minh Samsung Galaxy Watch5 Pro LTE 45mm Đen ', N'Việt Nam', 12990000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 1)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Hồng', CAST(N'2023-11-17' AS Date), N'Samsung đã cho ra mắt chiếc smartwatch có tên gọi là Galaxy Watch5 Pro LTE 45mm. Với những thay đổi về mặt thiết kế, chức năng theo dõi sức khỏe 24/7, đa dạng chế độ thể thao và hệ thống vệ tinh hiện đại hứa hẹn vẫn là sản phẩm làm hài lòng các tín đồ yêu công nghệ.', 12, N'Kính Sapphire', 44, N'Da tổng hợp', N'Samsung Galaxy Watch4', N'Đồng hồ thông minh Samsung Galaxy Watch4 40mm', N'Việt Nam', 3990000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 1)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Xanh dương', CAST(N'2023-11-17' AS Date), N'Samsung đã cho ra mắt chiếc smartwatch có tên gọi là Galaxy Watch5 Pro LTE 45mm. Với những thay đổi về mặt thiết kế, chức năng theo dõi sức khỏe 24/7, đa dạng chế độ thể thao và hệ thống vệ tinh hiện đại hứa hẹn vẫn là sản phẩm làm hài lòng các tín đồ yêu công nghệ.', 12, N'Kính Sapphire', 44, N'Da tổng hợp', N'Samsung Galaxy Watch4', N'Đồng hồ thông minh Samsung Galaxy Watch5 44mm', N'Việt Nam', 6490000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 1)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Trắng', CAST(N'2023-11-17' AS Date), N'Apple Watch Ultra 2 GPS + Cellular 49mm viền Titanium dây Ocean là chiếc đồng hồ thông minh của Apple gây được nhiều sự chú ý của giới truyền thông và người yêu công nghệ tại sự kiện Wonderlust năm 2023. Đồng hồ sở hữu vẻ ngoài vừa thời thượng vừa đậm chất thể thao vô cùng độc đáo, các tính năng bên trong cũng có cải tiến hứa hẹn sẽ làm hài lòng sự mong đợi của người dùng.', 12, N'Kính Sapphire', 44, N'Da tổng hợp', N'Apple Watch Ultra 2', N'Đồng hồ thông minh Apple Watch Ultra 2 GPS + Cellular 49mm viền Titanium dây Ocean', N'Việt Nam', 21990000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 2)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Vàng', CAST(N'2023-11-17' AS Date), N'Apple Watch Ultra 2 GPS + Cellular 49mm viền Titanium dây Ocean là chiếc đồng hồ thông minh của Apple gây được nhiều sự chú ý của giới truyền thông và người yêu công nghệ tại sự kiện Wonderlust năm 2023. Đồng hồ sở hữu vẻ ngoài vừa thời thượng vừa đậm chất thể thao vô cùng độc đáo, các tính năng bên trong cũng có cải tiến hứa hẹn sẽ làm hài lòng sự mong đợi của người dùng.', 12, N'Kính Sapphire', 44, N'Da tổng hợp', N'Apple Watch Series 9', N'Đồng hồ thông minh Apple Watch Series 9 GPS + Cellular 45mm viền thép dây thép', N'Việt Nam', 21590000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 2)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Đen', CAST(N'2023-11-17' AS Date), N'Apple Watch Ultra 2 GPS + Cellular 49mm viền Titanium dây Ocean là chiếc đồng hồ thông minh của Apple gây được nhiều sự chú ý của giới truyền thông và người yêu công nghệ tại sự kiện Wonderlust năm 2023. Đồng hồ sở hữu vẻ ngoài vừa thời thượng vừa đậm chất thể thao vô cùng độc đáo, các tính năng bên trong cũng có cải tiến hứa hẹn sẽ làm hài lòng sự mong đợi của người dùng.', 12, N'Kính Sapphire', 44, N'Cao su', N'Apple Watch Series 8', N'Đồng hồ thông minh Apple Watch Series 8 GPS + Cellular 41mm viền nhôm dây thể thao', N'Việt Nam', 11990000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 2)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Xanh đen', CAST(N'2023-11-17' AS Date), N'Apple Watch Ultra 2 GPS + Cellular 49mm viền Titanium dây Ocean là chiếc đồng hồ thông minh của Apple gây được nhiều sự chú ý của giới truyền thông và người yêu công nghệ tại sự kiện Wonderlust năm 2023. Đồng hồ sở hữu vẻ ngoài vừa thời thượng vừa đậm chất thể thao vô cùng độc đáo, các tính năng bên trong cũng có cải tiến hứa hẹn sẽ làm hài lòng sự mong đợi của người dùng.', 12, N'Kính Sapphire', 44, N'Cao su', N'Apple Watch Series 9', N'Đồng hồ thông minh Apple Watch Series 9 GPS 45mm viền nhôm dây thể thao', N'Việt Nam', 11290000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 2)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Tím', CAST(N'2023-11-17' AS Date), N'Garmin Vivoactive 5 là một chiếc smartwatch được thiết kế dành cho những người yêu thích thể thao và chú trọng theo dõi sức khỏe. Sản phẩm sở hữu nhiều tính năng thông minh như: Đo nhịp tim, VO2 Max, Body Battery, Garmin Coach,... hỗ trợ các mục tiêu cải thiện thể chất của người dùng.', 12, N'Kính Sapphire', 44, N'silicone', N'Garmin Vivoactive 5', N'Đồng hồ thông minh Garmin Vivoactive 5 42.2mm dây silicone', N'Việt Nam', 8290000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 3)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Tím', CAST(N'2023-11-17' AS Date), N'Đồng hồ thông minh Garmin Fenix 7X Pro Solar Titanium sẽ là một thiết bị hỗ trợ tuyệt vời dành cho những bạn yêu thích các môn thể thao ngoài trời. Tích hợp thêm các cảm biến theo dõi sức khỏe tiên tiến, hệ thống định vị hàng đầu mang đến cho người dùng những trải nghiệm tuyệt vời.', 12, N'Kính Sapphire', 44, N'silicone', N'Garmin Fenix 7X', N'Đồng hồ thông minh Garmin Fenix 7X Pro Solar Titanium', N'Việt Nam', 25990000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 3)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Vàng', CAST(N'2023-11-17' AS Date), N'Hãng đồng hồ thông minh thể thao lớn nhất thế giới Garmin đã trình làng thế hệ smartwatch dành cho người chạy bộ mới nhất trong năm của mình mang tên Garmin Forerunner 965. Với việc nâng cấp mạnh mẽ về màn hình và thời lượng pin, đây hứa hẹn là thế hệ Forerunner mang lại trải nghiệm tối ưu nhất dành cho các tín đồ của môn chạy bộ.', 12, N'Kính Sapphire', 44, N'silicone', N'Garmin Forerunner 965', N'Đồng hồ thông minh Garmin Forerunner 965 47.2mm', N'Việt Nam', 16490000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 3)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Trắng', CAST(N'2023-11-17' AS Date), N'Là mẫu smartwatch dành riêng cho phái đẹp với kiểu dáng nhỏ gọn, thời trang và gam màu bắt mắt, đồng thời còn được trang bị đầy đủ các tính năng theo dõi sức khỏe, luyện tập, thao tác kết nối đơn giản,... đồng hồ thông minh Garmin Lily sẽ là người bạn đồng hành lý tưởng dành cho các bạn nữ.', 5, N'Kính Sapphire', 44, N'silicone', N'Garmin Lily', N'Đồng hồ thông minh Garmin Lily 34.5mm', N'Việt Nam', 4990000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 3)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Hồng nhạt', CAST(N'2023-11-17' AS Date), N'Sở hữu khả năng nghe gọi 2 chiều, trang bị khả năng định vị tiên tiến cùng vô vàn tính năng thông minh, đồng hồ định vị trẻ em imoo Z1 dây TPU Hồng nhạt sẽ là một thiết bị liên lạc hữu ích dành cho các bé và phụ huynh mọi lúc mọi nơi như một thiết bị di động.', 5, N'Kính Sapphire', 44, N'silicone', N'Garmin Lily', N'Đồng Hồ Định Vị Trẻ Em imoo Z1 41mm Hồng Nhạt', N'Việt Nam', 2990000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 3)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Đen', CAST(N'2023-11-17' AS Date), N'Thương hiệu đồng hồ nổi tiếng đến từ Nhật Bản không ngừng cải tiến và cho ra mắt những dòng sản phẩm chất lượng phù hợp với nhiều đối tượng khách hàng. Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao, Edifice thiết kế hiện đại cùng nhiều tính năng vượt trội, Sheen với thiết kế cổ điển và sang trọng,…', 25, N'Kính Sapphire', 44, N'silicone', N'LQ-139AMV-1LDF', N'Đồng hồ CASIO 25 mm Nữ LQ-139AMV-1LDF', N'Việt Nam', 990000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 4)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Đen', CAST(N'2023-11-17' AS Date), N'Thương hiệu đồng hồ nổi tiếng đến từ Nhật Bản không ngừng cải tiến và cho ra mắt những dòng sản phẩm chất lượng phù hợp với nhiều đối tượng khách hàng. Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao, Edifice thiết kế hiện đại cùng nhiều tính năng vượt trội, Sheen với thiết kế cổ điển và sang trọng,…', 5, N'Kính Sapphire', 44, N'silicone', N'MTP-M305D-1AVDF', N'Đồng hồ Casio 34 mm Nam MTP-M305D-1AVDF', N'Việt Nam', 2990000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 4)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Đen', CAST(N'2023-11-17' AS Date), N'Thương hiệu đồng hồ nổi tiếng đến từ Nhật Bản không ngừng cải tiến và cho ra mắt những dòng sản phẩm chất lượng phù hợp với nhiều đối tượng khách hàng. Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao, Edifice thiết kế hiện đại cùng nhiều tính năng vượt trội, Sheen với thiết kế cổ điển và sang trọng,…', 10, N'Kính Sapphire', 44, N'silicone', N'WS-1600H-1AVDF', N'Đồng hồ Casio 42.1 mm Nam WS-1600H-1AVDF', N'Việt Nam', 1990000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 4)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Đen', CAST(N'2023-11-17' AS Date), N'Thương hiệu đồng hồ nổi tiếng đến từ Nhật Bản không ngừng cải tiến và cho ra mắt những dòng sản phẩm chất lượng phù hợp với nhiều đối tượng khách hàng. Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao, Edifice thiết kế hiện đại cùng nhiều tính năng vượt trội, Sheen với thiết kế cổ điển và sang trọng,…', 10, N'Kính Sapphire', 44, N'silicone', N'MTP-M305L-7AVDF', N'Đồng hồ Casio 34 mm Nam MTP-M305L-7AVDF', N'Việt Nam', 3550000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 4)
GO
INSERT [dbo].[products] ( [color], [create_date], [description], [discount], [face_material], [face_size], [frame_material], [model], [name], [origin], [price], [product_weight], [quantity], [screen_size], [sold_quantity], [update_date], [warranty_period], [wire_material], [id_brand]) VALUES ( N'Đen', CAST(N'2023-11-17' AS Date), N'Thương hiệu đồng hồ nổi tiếng đến từ Nhật Bản không ngừng cải tiến và cho ra mắt những dòng sản phẩm chất lượng phù hợp với nhiều đối tượng khách hàng. Những dòng sản phẩm nổi tiếng của Casio là: G-Shock với thiết kế mạnh mẽ cùng độ bền cao, Edifice thiết kế hiện đại cùng nhiều tính năng vượt trội, Sheen với thiết kế cổ điển và sang trọng,…', 5, N'Kính Sapphire', 44, N'silicone', N'MTP-VD03B-1AUDF', N'Đồng hồ Casio 41 mm Nam MTP-VD03B-1AUDF', N'Việt Nam', 1810000, 0.015, 100, 44, 0, CAST(N'2023-11-17' AS Date), 12, N'Thép không gỉ', 4)
GO
